import {NewProductPicture} from "./picture.model";


export interface NewProduct {
  id?: number; // Optional for new products

  infos: NewProductInfo,
  //availableQuantity: number;
  price: number;
  categoryId: number;
  subcategoryId: number;
  pictures: Array<NewProductPicture>,
}

export interface NewProductInfo {
  name: string;
  description: string;
  availableQuantity: number;
}

export interface CardProduct {
  id: number;
  name: string;
  description: string;
  availableQuantity: number;
  price: number;
  categoryId: number;
  categoryName: string;
  categoryDescription: string;
  subcategoryId: number;
  subcategoryName: string;
  cover: DisplayPicture;
}

export interface DisplayPicture {
  file?: string,
  fileContentType?: string,
  isCover?: boolean
}

export interface CreatedProduct {
  id: number; // Product ID generated by the backend.
}

export interface Product {
  id: number;
  name: string;
  description: string;
  availableQuantity: number;
  price: number;
  categoryId: number;
  categoryName: string;
  categoryDescription: string;
  subcategoryId: number;
  subcategoryName: string;
  pictures: Array<DisplayPicture>;
}

